DROP TABLE EXPEDIENTES;
DROP TABLE ALUMNOS;

DROP SEQUENCE seq_expedientes;

CREATE TABLE ALUMNOS (
    DNI VARCHAR(10) CONSTRAINT PK_ALUMNOS PRIMARY KEY,
    NOMBRE VARCHAR(40) CONSTRAINT NN_NOMBRE NOT NULL,
    EDAD NUMERIC(3) CONSTRAINT NN_EDAD NOT NULL,
    EMAIL VARCHAR(40) CONSTRAINT NN_EMAIL NOT NULL,
    CONSTRAINT CH_EDAD CHECK (EDAD > 0)
);

CREATE TABLE EXPEDIENTES (
    COD VARCHAR(10) CONSTRAINT PK_EXPEDIENTE PRIMARY KEY,
    DNI VARCHAR(10) CONSTRAINT NN_EXP_EXPEDIENTE NOT NULL,
    TITULACION VARCHAR(40) CONSTRAINT NN_TITULACION NOT NULL,
    NOTAMEDIA NUMERIC(4,2) CONSTRAINT NN_NOTAMEDIA NOT NULL,
    CREDSUP NUMERIC(3) CONSTRAINT NN_CREDSUP NOT NULL,
    CONSTRAINT FK_EXP_ALUMNOS FOREIGN KEY (DNI) REFERENCES ALUMNOS(DNI),
    CONSTRAINT CH_NOTAMEDIA CHECK (NOTAMEDIA > 0),
    CONSTRAINT CH_CREDSUP CHECK (CREDSUP > 0)
);

CREATE SEQUENCE seq_expedientes MINVALUE 1 MAXVALUE 9999999 START WITH 1 INCREMENT BY 1;

INSERT INTO ALUMNOS (DNI, NOMBRE, EDAD, EMAIL) VALUES
('70912312P', 'Juan Pérez', 20, 'juanperez@gmail.com'),
('23423423I', 'María López', 22, 'marialopez@gmail.com'),
('84565633R', 'Carlos Manuel', 21, 'carlosmanuel@gmail.com');


INSERT INTO EXPEDIENTES (COD, DNI, TITULACION, NOTAMEDIA, CREDSUP) VALUES
(nextval('seq_expedientes'), '70912312P', 'Ingeniería Informática', 8.5, 6),
(nextval('seq_expedientes'), '23423423I', 'Ingeniería Informática', 9.0, 6),
(nextval('seq_expedientes'), '84565633R', 'Física', 6.5, 4);



COMMIT;